baseURL = "/"
languageCode = "en-uk"
title = "My New Hugo Site"
theme = "Judy"
watch = true

[taxonomies]
  tag = ""
  group = ""
  category = ""

[menu]
    [[menu.main]]
    identifier = "home"
    name       = "Home"
    url        = "/"
    weight     = 1

    [[menu.main]]
    identifier = "news"
    name       = "News"
    url        = "/news"
    weight     = 2
