baseURL = "http://example.org/"
languageCode = "en-uk"
title = "My New Hugo Site"
theme = "Judy"
sectionPagesMenu = "main"

[menu]
    [[menu.main]]
    identifier = "home"
    name       = "Home"
    url        = "/"
    weight     = 1

    [[menu.main]]
    identifier = "news"
    name       = "News"
    url        = "/news"
    weight     = 2
